require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - "examples/*.rb"

#
# Opinionated cops
#

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Metrics/AbcSize:
  Max: 20

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 20

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

#
# Disabled cops
#

RSpec/VerifiedDoubles:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/BlockComments:
  Exclude:
    - "spec/spec_helper.rb"

Metrics/BlockLength:
  Exclude:
    - "spec/**/*_spec.rb"

Style/Proc:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false
